
{{- range $key, $value := .Values.operators }}
{{ if eq ($value.enabled | toString) "true" }}
{{ if eq ($value.namespace.create | toString) "true" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $value.namespace.name | quote }}
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: {{ $.Values.global.application_gitops_namespace }}
    {{- include "common.labels" $ | nindent 4 }}
  {{- if or ($value.namespace.descr) ($value.namespace.displayname) }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $value.syncwave | default "0" | quote }}
    {{- if $value.namespace.descr }}
    openshift.io/description: {{ $value.namespace.descr }}
    {{- end }}
    {{- if $value.namespace.displayname }}
    openshift.io/display-name: {{ $value.namespace.displayname }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}