operators:
  camelk-operator0:
    nexus: true
    namespace:
      name: camelk-test00
      create: false
    subscription:
      operatorName: red-hat-camel-k
      channel: 1.10.x
      approval: Automatic
      source: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorgroup:
      create: true
      notownnamespace: false
  camelk-operator1:
    nexus: true
    namespace:
      name: camelk-test01
      create: false
    subscription:
      operatorName: red-hat-camel-k
      channel: 1.10.x
      approval: Automatic
      source: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorgroup:
      create: true
      notownnamespace: false