operators:
  camelk-operator:
    enabled: true
    namespace:
      name: camelk-test03
      create: true
    subscription:
      channel: 1.10.x
      approval: Automatic
      operatorName: red-hat-camel-k
      source: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorgroup:
      create: true
      notownnamespace: false
    nexus:
      username: nexus
      password: nexus
    waitforcheck:
      crd: integrationplatforms.camel.apache.org
      create: true