operators:
  camelk-operator:
    enabled: true
    namespace:
      name: camelk-test00
      create: false
    subscription:
      channel: 1.10.x
      approval: Automatic
      operatorName: red-hat-camel-k
      source: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorgroup:
      create: true
      notownnamespace: false
    nexus:
      username: nexus
      password: "{+ORKcatQya0HQsu/G+qiJKoyXEKoPLsQPbTqUCm798w=}"
      mirror_url: http://nexusrepo-sonatype-nexus-service.dev-tool.svc.cluster.local:8081/repository/maven-public/