{{- range $key, $value := .Values.operators }}
{{ if eq ($value.enabled | toString) "true" }}
{{- if $value.operatorgroup.create }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: helper-operator
  namespace: {{ $value.namespace.name | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    argocd.argoproj.io/sync-wave: {{ $value.syncwave | default "1" | quote }}
{{- if $value.operatorgroup.notownnamespace }}
spec: {}
{{- else }}
spec:
  targetNamespaces:
  - {{ $value.namespace.name }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}