operators:
  amqs-operator0:
    enabled: true
    namespace:
      name: camelk-test00
      create: false
    subscription:
      channel: amq-streams-2.5.x
      approval: Automatic
      operatorName: amq-streams
      source: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorgroup:
      create: true
      notownnamespace: false
    kafka:
      name: api-infra
      version: "3.5.0"
      protocol_version: "3.5"
      replicas: 3
      storage: 10Gi
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
      systemuser: user-information
    zookeeper:
      replicas: 3
      storage: 10Gi
      limits:
        cpu: "0.5"
        memory: 1Gi
      requests:
        cpu: "0.5"
        memory: 1Gi
    kafkaconnect:
      name: user-information-connect
      replicas: "3"
      replication_factor: "3"
      limits:
        cpu: "1"
        memory: 3Gi
      requests:
        cpu: "1"
        memory: 3Gi
    kafkaconnector:
      database:
        hostname: my-oracle-db.oracledb.svc.cluster.local
        port: 1521
        dbname: XEPDB1
      name: user-information-connect
  amqs-operator1:
    enabled: true
    namespace:
      name: camelk-test01
      create: false
    subscription:
      channel: amq-streams-2.5.x
      approval: Automatic
      operatorName: amq-streams
      source: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorgroup:
      create: true
      notownnamespace: false
    kafka:
      version: "3.5.0"
      protocol_version: "3.5"
      replicas: 3
      storage: 10Gi
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
    zookeeper:
      replicas: 3
      storage: 10Gi
      limits:
        cpu: "0.5"
        memory: 1Gi
      requests:
        cpu: "0.5"
        memory: 1Gi