operators:
  camelk-operator:
    enabled: true
    namespace:
      name: amqs-test00
      create: true
    subscription:
      channel: 2.5.x
      approval: Automatic
      operatorName: amq-streams
      source: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorgroup:
      create: true
      notownnamespace: false