operators:
  amqs-operator0:
    enabled: true
    kafka:
      version: 3.5.0
      replicas: 3
    namespace:
      name: amqs-test00
      create: false
    subscription:
      channel: 2.5.x
      approval: Automatic
      operatorName: amq-streams
      source: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorgroup:
      create: true
      notownnamespace: false