operators:
  amqs-operator0:
    enabled: true
    kafka:
      version: 3.5.0
      protocol_version: 3.5
      replicas: 3
      storage: 10Gi
      limits:
        cpu: 1
        memroy: 2Gi
      requests:
        cpu: 1
        memroy: 2Gi
    zookeeper:
      replicas: 3
      storage: 10Gi
      limits:
        cpu: 0.5
        memroy: 1Gi
      requests:
        cpu: 0.5
        memroy: 1Gi
    namespace:
      name: amqs-test00
      create: false
    subscription:
      channel: 2.5.x
      approval: Automatic
      operatorName: amq-streams
      source: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorgroup:
      create: true
      notownnamespace: false