apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: onboarding
  namespace: openshift-gitops
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - git:
        files:
          - path: tenant-projects/namespace/*/values.yaml
        repoURL: "https://github.com/hashnao/gitops-practice"
        revision: main
  template:
    metadata:
      name: "{{ index .path.segments 1 | normalize }}-{{ .path.basename }}"
    spec:
      info:
        - name: Description
          value: Create namespaces and add users to the group
      destination:
        server: "https://kubernetes.default.svc"
      project: default
      source:
        repoURL: "https://github.com/hashnao/gitops-practice"
        targetRevision: main
        path: clusters/helper-proj-onboarding
        helm:
          valueFiles:
            - "/{{ .path.path }}/values.yaml"
            - /tenant-projects/values-global.yaml
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
