{{- range $key, $value := .Values.namespaces }}
{{ if eq ( .enabled | toString) "true" }}

{{- $default_policies := index $value "default_policies" | default dict }}

{{- $disable_allow_from_ingress := index $default_policies "disable_allow_from_ingress" | default "false" }}
{{ if ne ($disable_allow_from_ingress | toString) "true" }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-ingress
  namespace: {{ $value.name | replace "_" "-" | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          policy-group.network.openshift.io/ingress: ""
  podSelector: {}
  policyTypes:
  - Ingress
{{- end }}

{{- $disable_allow_from_monitoring := index $default_policies "disable_allow_from_monitoring" | default "false" }}
{{ if ne ($disable_allow_from_monitoring | toString) "true" }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-monitoring
  namespace: {{ $value.name | replace "_" "-" | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: monitoring
  podSelector: {}
  policyTypes:
  - Ingress
{{- end }}

{{- $disable_allow_from_same_namespace := index $default_policies "disable_allow_from_same_namespace" | default "false" }}
{{ if ne ($disable_allow_from_same_namespace | toString) "true" }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace
  namespace: {{ $value.name | replace "_" "-" | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  podSelector:
  ingress:
  - from:
    - podSelector: {}
{{- end }}

{{- $disable_allow_kube_apiserver := index $default_policies "disable_allow_kube_apiserver" | default "false" }}
{{ if ne ($disable_allow_kube_apiserver | toString) "true" }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-kube-apiserver-operator
  namespace: {{ $value.name | replace "_" "-" | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-kube-apiserver-operator
      podSelector:
        matchLabels:
          app: kube-apiserver-operator
  policyTypes:
  - Ingress
{{- end }}

{{- $disable_deny_all_egress := index $default_policies "disable_deny_all_egress" | default "false" }}
{{ if ne ($disable_deny_all_egress | toString) "true" }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: {{ $value.name | replace "_" "-" | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
{{- end }}
{{- end }}
{{- end }}
