{{- range $key, $value := .Values.operators }}
{{- if eq ($value.enabled | toString) "true" }}
{{- if $value.kafka }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ $value.kafka.systemuser }}
  namespace: {{ $value.namespace.name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $value.syncwave | default "3" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    strimzi.io/cluster: api-infra
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          patternType: prefix
          name: {{ $value.kafka.systemuser }}
        operations:
          - All
      - resource:
          type: group
          patternType: prefix
          name: {{ $value.kafka.systemuser }}
        operations:
          - All
      - resource:
          type: cluster
        operations:
          - IdempotentWrite
{{- end }}
{{- end }}
{{- end }}