{{- range $key, $value := .Values.operators }}
{{- if eq ($value.enabled | toString) "true" }}
{{- if $value.kafka }}
{{- if $value.kafka.systemusers }}
{{- range $key_user, $value_user := .kafka.systemusers }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .name }}
  namespace: {{ $value.namespace.name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $value.syncwave | default "3" | quote }}
  labels:
    strimzi.io/cluster: api-infra
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          patternType: prefix
          name: {{ .name }}
        operation: All
      - resource:
          type: group
          patternType: prefix
          name: {{ .name }}
        operation: All
      - resource:
          type: cluster
        operation: IdempotentWrite
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}