{{- if .Values.waitforcheck }}

apiVersion: v1
kind: Pod
metadata:
  name: cluster-check 
  namespace: {{ $value.namespace.name | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $value.syncwave | default "1" | quote }}
spec:
  containers:
  - name: crd-check 
    image: quay.io/openshift/origin-cli:latest
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'while [ true ]; do oc get crd {{ $value.waitforcheck.crd }} ; if [ $? -eq 0 ]; then break; fi ; sleep 5s; done']
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  serviceAccount: default
  serviceAccountName: default
{{- end }}