apiVersion: v2
name: helper-proj-onboarding
description: This Chart shall deploy namespaces and their depending resources, like NetworkPolicies or Quotas etc.
version: 1.0.27
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/helper-proj-onboarding
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/helping.png
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
sources:
  - https://github.com/tjungbauer/helm-charts
keywords:
  - helper
  - subchart
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: fixed
      description: Signing Chart
