apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: camelk
  namespace: openshift-gitops
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - git:
        files:
          - path: tenant-projects/camelk/*/values.yaml
        repoURL: "https://github.com/hashnao/gitops-practice"
        revision: main
  template:
    metadata:
      name: "{{ index .path.segments 1 | normalize }}-{{ .path.basename }}"
    spec:
      info:
        - name: Description
          value: Provisioning Camel K Operator
      destination:
        server: "https://kubernetes.default.svc"
      project: default
      source:
        repoURL: "https://github.com/hashnao/gitops-practice"
        targetRevision: main
        path: clusters/helper-operator
        helm:
          valueFiles:
            - "/{{ .path.path }}/values.yaml"
            - /tenant-projects/values-global.yaml
          parameters:
          - name: "operators.camelk-operator.nexus.username"
            value: <USERNAME>
          - name: "operators.camelk-operator.nexus.password"
            value: <PASSWORD>
          - name: "operators.camelk-operator.nexus.mirror_url"
            value: <NEXUS_URL>
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - Validate=false